// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: join_response.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "join_response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace raft_msg {
class JoinResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<JoinResponse> {
} _JoinResponse_default_instance_;

namespace protobuf_join_5fresponse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinResponse, success_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinResponse, passwd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinResponse, join_err_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinResponse, myname_),
  2,
  0,
  3,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 8, sizeof(JoinResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_JoinResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "join_response.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _JoinResponse_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::raft_msg::protobuf_raft_5fenum_2eproto::InitDefaults();
  _JoinResponse_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\023join_response.proto\022\010raft_msg\032\017raft_en"
      "um.proto\"f\n\014JoinResponse\022\017\n\007success\030\001 \002("
      "\010\022\016\n\006passwd\030\002 \002(\t\022%\n\010join_err\030\003 \001(\0162\023.ra"
      "ft_msg.JoinError\022\016\n\006myname\030\004 \002(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 152);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "join_response.proto", &protobuf_RegisterTypes);
  ::raft_msg::protobuf_raft_5fenum_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_join_5fresponse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JoinResponse::kSuccessFieldNumber;
const int JoinResponse::kPasswdFieldNumber;
const int JoinResponse::kJoinErrFieldNumber;
const int JoinResponse::kMynameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JoinResponse::JoinResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_join_5fresponse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:raft_msg.JoinResponse)
}
JoinResponse::JoinResponse(const JoinResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_passwd()) {
    passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
  }
  myname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_myname()) {
    myname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.myname_);
  }
  ::memcpy(&success_, &from.success_,
    reinterpret_cast<char*>(&join_err_) -
    reinterpret_cast<char*>(&success_) + sizeof(join_err_));
  // @@protoc_insertion_point(copy_constructor:raft_msg.JoinResponse)
}

void JoinResponse::SharedCtor() {
  _cached_size_ = 0;
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  myname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&success_, 0, reinterpret_cast<char*>(&join_err_) -
    reinterpret_cast<char*>(&success_) + sizeof(join_err_));
}

JoinResponse::~JoinResponse() {
  // @@protoc_insertion_point(destructor:raft_msg.JoinResponse)
  SharedDtor();
}

void JoinResponse::SharedDtor() {
  passwd_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  myname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void JoinResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JoinResponse::descriptor() {
  protobuf_join_5fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_join_5fresponse_2eproto::file_level_metadata[0].descriptor;
}

const JoinResponse& JoinResponse::default_instance() {
  protobuf_join_5fresponse_2eproto::InitDefaults();
  return *internal_default_instance();
}

JoinResponse* JoinResponse::New(::google::protobuf::Arena* arena) const {
  JoinResponse* n = new JoinResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JoinResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:raft_msg.JoinResponse)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_passwd()) {
      GOOGLE_DCHECK(!passwd_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*passwd_.UnsafeRawStringPointer())->clear();
    }
    if (has_myname()) {
      GOOGLE_DCHECK(!myname_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*myname_.UnsafeRawStringPointer())->clear();
    }
  }
  if (_has_bits_[0 / 32] & 12u) {
    ::memset(&success_, 0, reinterpret_cast<char*>(&join_err_) -
      reinterpret_cast<char*>(&success_) + sizeof(join_err_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool JoinResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:raft_msg.JoinResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool success = 1;
      case 1: {
        if (tag == 8u) {
          set_has_success();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &success_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string passwd = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_passwd()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->passwd().data(), this->passwd().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "raft_msg.JoinResponse.passwd");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .raft_msg.JoinError join_err = 3;
      case 3: {
        if (tag == 24u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::raft_msg::JoinError_IsValid(value)) {
            set_join_err(static_cast< ::raft_msg::JoinError >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string myname = 4;
      case 4: {
        if (tag == 34u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_myname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->myname().data(), this->myname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "raft_msg.JoinResponse.myname");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:raft_msg.JoinResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:raft_msg.JoinResponse)
  return false;
#undef DO_
}

void JoinResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:raft_msg.JoinResponse)
  // required bool success = 1;
  if (has_success()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->success(), output);
  }

  // required string passwd = 2;
  if (has_passwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->passwd().data(), this->passwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinResponse.passwd");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->passwd(), output);
  }

  // optional .raft_msg.JoinError join_err = 3;
  if (has_join_err()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->join_err(), output);
  }

  // required string myname = 4;
  if (has_myname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->myname().data(), this->myname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinResponse.myname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->myname(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:raft_msg.JoinResponse)
}

::google::protobuf::uint8* JoinResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:raft_msg.JoinResponse)
  // required bool success = 1;
  if (has_success()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->success(), target);
  }

  // required string passwd = 2;
  if (has_passwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->passwd().data(), this->passwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinResponse.passwd");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->passwd(), target);
  }

  // optional .raft_msg.JoinError join_err = 3;
  if (has_join_err()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->join_err(), target);
  }

  // required string myname = 4;
  if (has_myname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->myname().data(), this->myname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinResponse.myname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->myname(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raft_msg.JoinResponse)
  return target;
}

size_t JoinResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:raft_msg.JoinResponse)
  size_t total_size = 0;

  if (has_passwd()) {
    // required string passwd = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->passwd());
  }

  if (has_myname()) {
    // required string myname = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->myname());
  }

  if (has_success()) {
    // required bool success = 1;
    total_size += 1 + 1;
  }

  return total_size;
}
size_t JoinResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:raft_msg.JoinResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string passwd = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->passwd());

    // required string myname = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->myname());

    // required bool success = 1;
    total_size += 1 + 1;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional .raft_msg.JoinError join_err = 3;
  if (has_join_err()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->join_err());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JoinResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:raft_msg.JoinResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const JoinResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const JoinResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:raft_msg.JoinResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:raft_msg.JoinResponse)
    MergeFrom(*source);
  }
}

void JoinResponse::MergeFrom(const JoinResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:raft_msg.JoinResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 15u) {
    if (from.has_passwd()) {
      set_has_passwd();
      passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
    }
    if (from.has_myname()) {
      set_has_myname();
      myname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.myname_);
    }
    if (from.has_success()) {
      set_success(from.success());
    }
    if (from.has_join_err()) {
      set_join_err(from.join_err());
    }
  }
}

void JoinResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:raft_msg.JoinResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JoinResponse::CopyFrom(const JoinResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:raft_msg.JoinResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JoinResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void JoinResponse::Swap(JoinResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JoinResponse::InternalSwap(JoinResponse* other) {
  passwd_.Swap(&other->passwd_);
  myname_.Swap(&other->myname_);
  std::swap(success_, other->success_);
  std::swap(join_err_, other->join_err_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JoinResponse::GetMetadata() const {
  protobuf_join_5fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_join_5fresponse_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JoinResponse

// required bool success = 1;
bool JoinResponse::has_success() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void JoinResponse::set_has_success() {
  _has_bits_[0] |= 0x00000004u;
}
void JoinResponse::clear_has_success() {
  _has_bits_[0] &= ~0x00000004u;
}
void JoinResponse::clear_success() {
  success_ = false;
  clear_has_success();
}
bool JoinResponse::success() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinResponse.success)
  return success_;
}
void JoinResponse::set_success(bool value) {
  set_has_success();
  success_ = value;
  // @@protoc_insertion_point(field_set:raft_msg.JoinResponse.success)
}

// required string passwd = 2;
bool JoinResponse::has_passwd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JoinResponse::set_has_passwd() {
  _has_bits_[0] |= 0x00000001u;
}
void JoinResponse::clear_has_passwd() {
  _has_bits_[0] &= ~0x00000001u;
}
void JoinResponse::clear_passwd() {
  passwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_passwd();
}
const ::std::string& JoinResponse::passwd() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinResponse.passwd)
  return passwd_.GetNoArena();
}
void JoinResponse::set_passwd(const ::std::string& value) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinResponse.passwd)
}
#if LANG_CXX11
void JoinResponse::set_passwd(::std::string&& value) {
  set_has_passwd();
  passwd_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinResponse.passwd)
}
#endif
void JoinResponse::set_passwd(const char* value) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinResponse.passwd)
}
void JoinResponse::set_passwd(const char* value, size_t size) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinResponse.passwd)
}
::std::string* JoinResponse::mutable_passwd() {
  set_has_passwd();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinResponse.passwd)
  return passwd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JoinResponse::release_passwd() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinResponse.passwd)
  clear_has_passwd();
  return passwd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JoinResponse::set_allocated_passwd(::std::string* passwd) {
  if (passwd != NULL) {
    set_has_passwd();
  } else {
    clear_has_passwd();
  }
  passwd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), passwd);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinResponse.passwd)
}

// optional .raft_msg.JoinError join_err = 3;
bool JoinResponse::has_join_err() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void JoinResponse::set_has_join_err() {
  _has_bits_[0] |= 0x00000008u;
}
void JoinResponse::clear_has_join_err() {
  _has_bits_[0] &= ~0x00000008u;
}
void JoinResponse::clear_join_err() {
  join_err_ = 0;
  clear_has_join_err();
}
::raft_msg::JoinError JoinResponse::join_err() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinResponse.join_err)
  return static_cast< ::raft_msg::JoinError >(join_err_);
}
void JoinResponse::set_join_err(::raft_msg::JoinError value) {
  assert(::raft_msg::JoinError_IsValid(value));
  set_has_join_err();
  join_err_ = value;
  // @@protoc_insertion_point(field_set:raft_msg.JoinResponse.join_err)
}

// required string myname = 4;
bool JoinResponse::has_myname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void JoinResponse::set_has_myname() {
  _has_bits_[0] |= 0x00000002u;
}
void JoinResponse::clear_has_myname() {
  _has_bits_[0] &= ~0x00000002u;
}
void JoinResponse::clear_myname() {
  myname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_myname();
}
const ::std::string& JoinResponse::myname() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinResponse.myname)
  return myname_.GetNoArena();
}
void JoinResponse::set_myname(const ::std::string& value) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinResponse.myname)
}
#if LANG_CXX11
void JoinResponse::set_myname(::std::string&& value) {
  set_has_myname();
  myname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinResponse.myname)
}
#endif
void JoinResponse::set_myname(const char* value) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinResponse.myname)
}
void JoinResponse::set_myname(const char* value, size_t size) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinResponse.myname)
}
::std::string* JoinResponse::mutable_myname() {
  set_has_myname();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinResponse.myname)
  return myname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JoinResponse::release_myname() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinResponse.myname)
  clear_has_myname();
  return myname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JoinResponse::set_allocated_myname(::std::string* myname) {
  if (myname != NULL) {
    set_has_myname();
  } else {
    clear_has_myname();
  }
  myname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), myname);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinResponse.myname)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace raft_msg

// @@protoc_insertion_point(global_scope)
