// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: join_request.proto

#ifndef PROTOBUF_join_5frequest_2eproto__INCLUDED
#define PROTOBUF_join_5frequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace raft_msg {
class JoinRequest;
class JoinRequestDefaultTypeInternal;
extern JoinRequestDefaultTypeInternal _JoinRequest_default_instance_;
}  // namespace raft_msg

namespace raft_msg {

namespace protobuf_join_5frequest_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_join_5frequest_2eproto

// ===================================================================

class JoinRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_msg.JoinRequest) */ {
 public:
  JoinRequest();
  virtual ~JoinRequest();

  JoinRequest(const JoinRequest& from);

  inline JoinRequest& operator=(const JoinRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JoinRequest& default_instance();

  static inline const JoinRequest* internal_default_instance() {
    return reinterpret_cast<const JoinRequest*>(
               &_JoinRequest_default_instance_);
  }

  void Swap(JoinRequest* other);

  // implements Message ----------------------------------------------

  inline JoinRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  JoinRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const JoinRequest& from);
  void MergeFrom(const JoinRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(JoinRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string ipaddr = 1;
  bool has_ipaddr() const;
  void clear_ipaddr();
  static const int kIpaddrFieldNumber = 1;
  const ::std::string& ipaddr() const;
  void set_ipaddr(const ::std::string& value);
  #if LANG_CXX11
  void set_ipaddr(::std::string&& value);
  #endif
  void set_ipaddr(const char* value);
  void set_ipaddr(const char* value, size_t size);
  ::std::string* mutable_ipaddr();
  ::std::string* release_ipaddr();
  void set_allocated_ipaddr(::std::string* ipaddr);

  // required string passwd = 2;
  bool has_passwd() const;
  void clear_passwd();
  static const int kPasswdFieldNumber = 2;
  const ::std::string& passwd() const;
  void set_passwd(const ::std::string& value);
  #if LANG_CXX11
  void set_passwd(::std::string&& value);
  #endif
  void set_passwd(const char* value);
  void set_passwd(const char* value, size_t size);
  ::std::string* mutable_passwd();
  ::std::string* release_passwd();
  void set_allocated_passwd(::std::string* passwd);

  // required string myname = 3;
  bool has_myname() const;
  void clear_myname();
  static const int kMynameFieldNumber = 3;
  const ::std::string& myname() const;
  void set_myname(const ::std::string& value);
  #if LANG_CXX11
  void set_myname(::std::string&& value);
  #endif
  void set_myname(const char* value);
  void set_myname(const char* value, size_t size);
  ::std::string* mutable_myname();
  ::std::string* release_myname();
  void set_allocated_myname(::std::string* myname);

  // @@protoc_insertion_point(class_scope:raft_msg.JoinRequest)
 private:
  void set_has_ipaddr();
  void clear_has_ipaddr();
  void set_has_passwd();
  void clear_has_passwd();
  void set_has_myname();
  void clear_has_myname();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr ipaddr_;
  ::google::protobuf::internal::ArenaStringPtr passwd_;
  ::google::protobuf::internal::ArenaStringPtr myname_;
  friend struct  protobuf_join_5frequest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// JoinRequest

// required string ipaddr = 1;
inline bool JoinRequest::has_ipaddr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JoinRequest::set_has_ipaddr() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JoinRequest::clear_has_ipaddr() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JoinRequest::clear_ipaddr() {
  ipaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ipaddr();
}
inline const ::std::string& JoinRequest::ipaddr() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinRequest.ipaddr)
  return ipaddr_.GetNoArena();
}
inline void JoinRequest::set_ipaddr(const ::std::string& value) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinRequest.ipaddr)
}
#if LANG_CXX11
inline void JoinRequest::set_ipaddr(::std::string&& value) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinRequest.ipaddr)
}
#endif
inline void JoinRequest::set_ipaddr(const char* value) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinRequest.ipaddr)
}
inline void JoinRequest::set_ipaddr(const char* value, size_t size) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinRequest.ipaddr)
}
inline ::std::string* JoinRequest::mutable_ipaddr() {
  set_has_ipaddr();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinRequest.ipaddr)
  return ipaddr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JoinRequest::release_ipaddr() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinRequest.ipaddr)
  clear_has_ipaddr();
  return ipaddr_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JoinRequest::set_allocated_ipaddr(::std::string* ipaddr) {
  if (ipaddr != NULL) {
    set_has_ipaddr();
  } else {
    clear_has_ipaddr();
  }
  ipaddr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ipaddr);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinRequest.ipaddr)
}

// required string passwd = 2;
inline bool JoinRequest::has_passwd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JoinRequest::set_has_passwd() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JoinRequest::clear_has_passwd() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JoinRequest::clear_passwd() {
  passwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_passwd();
}
inline const ::std::string& JoinRequest::passwd() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinRequest.passwd)
  return passwd_.GetNoArena();
}
inline void JoinRequest::set_passwd(const ::std::string& value) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinRequest.passwd)
}
#if LANG_CXX11
inline void JoinRequest::set_passwd(::std::string&& value) {
  set_has_passwd();
  passwd_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinRequest.passwd)
}
#endif
inline void JoinRequest::set_passwd(const char* value) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinRequest.passwd)
}
inline void JoinRequest::set_passwd(const char* value, size_t size) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinRequest.passwd)
}
inline ::std::string* JoinRequest::mutable_passwd() {
  set_has_passwd();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinRequest.passwd)
  return passwd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JoinRequest::release_passwd() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinRequest.passwd)
  clear_has_passwd();
  return passwd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JoinRequest::set_allocated_passwd(::std::string* passwd) {
  if (passwd != NULL) {
    set_has_passwd();
  } else {
    clear_has_passwd();
  }
  passwd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), passwd);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinRequest.passwd)
}

// required string myname = 3;
inline bool JoinRequest::has_myname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void JoinRequest::set_has_myname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void JoinRequest::clear_has_myname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void JoinRequest::clear_myname() {
  myname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_myname();
}
inline const ::std::string& JoinRequest::myname() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinRequest.myname)
  return myname_.GetNoArena();
}
inline void JoinRequest::set_myname(const ::std::string& value) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinRequest.myname)
}
#if LANG_CXX11
inline void JoinRequest::set_myname(::std::string&& value) {
  set_has_myname();
  myname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinRequest.myname)
}
#endif
inline void JoinRequest::set_myname(const char* value) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinRequest.myname)
}
inline void JoinRequest::set_myname(const char* value, size_t size) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinRequest.myname)
}
inline ::std::string* JoinRequest::mutable_myname() {
  set_has_myname();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinRequest.myname)
  return myname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JoinRequest::release_myname() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinRequest.myname)
  clear_has_myname();
  return myname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JoinRequest::set_allocated_myname(::std::string* myname) {
  if (myname != NULL) {
    set_has_myname();
  } else {
    clear_has_myname();
  }
  myname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), myname);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinRequest.myname)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace raft_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_join_5frequest_2eproto__INCLUDED
