// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: join_request.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "join_request.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace raft_msg {
class JoinRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<JoinRequest> {
} _JoinRequest_default_instance_;

namespace protobuf_join_5frequest_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinRequest, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinRequest, ipaddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinRequest, passwd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinRequest, myname_),
  0,
  1,
  2,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(JoinRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_JoinRequest_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "join_request.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _JoinRequest_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _JoinRequest_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\022join_request.proto\022\010raft_msg\"=\n\013JoinRe"
      "quest\022\016\n\006ipaddr\030\001 \002(\t\022\016\n\006passwd\030\002 \002(\t\022\016\n"
      "\006myname\030\003 \002(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 93);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "join_request.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_join_5frequest_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JoinRequest::kIpaddrFieldNumber;
const int JoinRequest::kPasswdFieldNumber;
const int JoinRequest::kMynameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JoinRequest::JoinRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_join_5frequest_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:raft_msg.JoinRequest)
}
JoinRequest::JoinRequest(const JoinRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ipaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_ipaddr()) {
    ipaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddr_);
  }
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_passwd()) {
    passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
  }
  myname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_myname()) {
    myname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.myname_);
  }
  // @@protoc_insertion_point(copy_constructor:raft_msg.JoinRequest)
}

void JoinRequest::SharedCtor() {
  _cached_size_ = 0;
  ipaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  myname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

JoinRequest::~JoinRequest() {
  // @@protoc_insertion_point(destructor:raft_msg.JoinRequest)
  SharedDtor();
}

void JoinRequest::SharedDtor() {
  ipaddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  passwd_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  myname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void JoinRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JoinRequest::descriptor() {
  protobuf_join_5frequest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_join_5frequest_2eproto::file_level_metadata[0].descriptor;
}

const JoinRequest& JoinRequest::default_instance() {
  protobuf_join_5frequest_2eproto::InitDefaults();
  return *internal_default_instance();
}

JoinRequest* JoinRequest::New(::google::protobuf::Arena* arena) const {
  JoinRequest* n = new JoinRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JoinRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:raft_msg.JoinRequest)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_ipaddr()) {
      GOOGLE_DCHECK(!ipaddr_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*ipaddr_.UnsafeRawStringPointer())->clear();
    }
    if (has_passwd()) {
      GOOGLE_DCHECK(!passwd_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*passwd_.UnsafeRawStringPointer())->clear();
    }
    if (has_myname()) {
      GOOGLE_DCHECK(!myname_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*myname_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool JoinRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:raft_msg.JoinRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string ipaddr = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ipaddr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ipaddr().data(), this->ipaddr().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "raft_msg.JoinRequest.ipaddr");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string passwd = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_passwd()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->passwd().data(), this->passwd().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "raft_msg.JoinRequest.passwd");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string myname = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_myname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->myname().data(), this->myname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "raft_msg.JoinRequest.myname");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:raft_msg.JoinRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:raft_msg.JoinRequest)
  return false;
#undef DO_
}

void JoinRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:raft_msg.JoinRequest)
  // required string ipaddr = 1;
  if (has_ipaddr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ipaddr().data(), this->ipaddr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinRequest.ipaddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ipaddr(), output);
  }

  // required string passwd = 2;
  if (has_passwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->passwd().data(), this->passwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinRequest.passwd");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->passwd(), output);
  }

  // required string myname = 3;
  if (has_myname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->myname().data(), this->myname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinRequest.myname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->myname(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:raft_msg.JoinRequest)
}

::google::protobuf::uint8* JoinRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:raft_msg.JoinRequest)
  // required string ipaddr = 1;
  if (has_ipaddr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ipaddr().data(), this->ipaddr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinRequest.ipaddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ipaddr(), target);
  }

  // required string passwd = 2;
  if (has_passwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->passwd().data(), this->passwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinRequest.passwd");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->passwd(), target);
  }

  // required string myname = 3;
  if (has_myname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->myname().data(), this->myname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "raft_msg.JoinRequest.myname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->myname(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raft_msg.JoinRequest)
  return target;
}

size_t JoinRequest::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:raft_msg.JoinRequest)
  size_t total_size = 0;

  if (has_ipaddr()) {
    // required string ipaddr = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ipaddr());
  }

  if (has_passwd()) {
    // required string passwd = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->passwd());
  }

  if (has_myname()) {
    // required string myname = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->myname());
  }

  return total_size;
}
size_t JoinRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:raft_msg.JoinRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string ipaddr = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ipaddr());

    // required string passwd = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->passwd());

    // required string myname = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->myname());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JoinRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:raft_msg.JoinRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const JoinRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const JoinRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:raft_msg.JoinRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:raft_msg.JoinRequest)
    MergeFrom(*source);
  }
}

void JoinRequest::MergeFrom(const JoinRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:raft_msg.JoinRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 7u) {
    if (from.has_ipaddr()) {
      set_has_ipaddr();
      ipaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddr_);
    }
    if (from.has_passwd()) {
      set_has_passwd();
      passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
    }
    if (from.has_myname()) {
      set_has_myname();
      myname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.myname_);
    }
  }
}

void JoinRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:raft_msg.JoinRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JoinRequest::CopyFrom(const JoinRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:raft_msg.JoinRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JoinRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void JoinRequest::Swap(JoinRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JoinRequest::InternalSwap(JoinRequest* other) {
  ipaddr_.Swap(&other->ipaddr_);
  passwd_.Swap(&other->passwd_);
  myname_.Swap(&other->myname_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JoinRequest::GetMetadata() const {
  protobuf_join_5frequest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_join_5frequest_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JoinRequest

// required string ipaddr = 1;
bool JoinRequest::has_ipaddr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JoinRequest::set_has_ipaddr() {
  _has_bits_[0] |= 0x00000001u;
}
void JoinRequest::clear_has_ipaddr() {
  _has_bits_[0] &= ~0x00000001u;
}
void JoinRequest::clear_ipaddr() {
  ipaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ipaddr();
}
const ::std::string& JoinRequest::ipaddr() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinRequest.ipaddr)
  return ipaddr_.GetNoArena();
}
void JoinRequest::set_ipaddr(const ::std::string& value) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinRequest.ipaddr)
}
#if LANG_CXX11
void JoinRequest::set_ipaddr(::std::string&& value) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinRequest.ipaddr)
}
#endif
void JoinRequest::set_ipaddr(const char* value) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinRequest.ipaddr)
}
void JoinRequest::set_ipaddr(const char* value, size_t size) {
  set_has_ipaddr();
  ipaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinRequest.ipaddr)
}
::std::string* JoinRequest::mutable_ipaddr() {
  set_has_ipaddr();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinRequest.ipaddr)
  return ipaddr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JoinRequest::release_ipaddr() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinRequest.ipaddr)
  clear_has_ipaddr();
  return ipaddr_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JoinRequest::set_allocated_ipaddr(::std::string* ipaddr) {
  if (ipaddr != NULL) {
    set_has_ipaddr();
  } else {
    clear_has_ipaddr();
  }
  ipaddr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ipaddr);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinRequest.ipaddr)
}

// required string passwd = 2;
bool JoinRequest::has_passwd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void JoinRequest::set_has_passwd() {
  _has_bits_[0] |= 0x00000002u;
}
void JoinRequest::clear_has_passwd() {
  _has_bits_[0] &= ~0x00000002u;
}
void JoinRequest::clear_passwd() {
  passwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_passwd();
}
const ::std::string& JoinRequest::passwd() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinRequest.passwd)
  return passwd_.GetNoArena();
}
void JoinRequest::set_passwd(const ::std::string& value) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinRequest.passwd)
}
#if LANG_CXX11
void JoinRequest::set_passwd(::std::string&& value) {
  set_has_passwd();
  passwd_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinRequest.passwd)
}
#endif
void JoinRequest::set_passwd(const char* value) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinRequest.passwd)
}
void JoinRequest::set_passwd(const char* value, size_t size) {
  set_has_passwd();
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinRequest.passwd)
}
::std::string* JoinRequest::mutable_passwd() {
  set_has_passwd();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinRequest.passwd)
  return passwd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JoinRequest::release_passwd() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinRequest.passwd)
  clear_has_passwd();
  return passwd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JoinRequest::set_allocated_passwd(::std::string* passwd) {
  if (passwd != NULL) {
    set_has_passwd();
  } else {
    clear_has_passwd();
  }
  passwd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), passwd);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinRequest.passwd)
}

// required string myname = 3;
bool JoinRequest::has_myname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void JoinRequest::set_has_myname() {
  _has_bits_[0] |= 0x00000004u;
}
void JoinRequest::clear_has_myname() {
  _has_bits_[0] &= ~0x00000004u;
}
void JoinRequest::clear_myname() {
  myname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_myname();
}
const ::std::string& JoinRequest::myname() const {
  // @@protoc_insertion_point(field_get:raft_msg.JoinRequest.myname)
  return myname_.GetNoArena();
}
void JoinRequest::set_myname(const ::std::string& value) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_msg.JoinRequest.myname)
}
#if LANG_CXX11
void JoinRequest::set_myname(::std::string&& value) {
  set_has_myname();
  myname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raft_msg.JoinRequest.myname)
}
#endif
void JoinRequest::set_myname(const char* value) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_msg.JoinRequest.myname)
}
void JoinRequest::set_myname(const char* value, size_t size) {
  set_has_myname();
  myname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_msg.JoinRequest.myname)
}
::std::string* JoinRequest::mutable_myname() {
  set_has_myname();
  // @@protoc_insertion_point(field_mutable:raft_msg.JoinRequest.myname)
  return myname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JoinRequest::release_myname() {
  // @@protoc_insertion_point(field_release:raft_msg.JoinRequest.myname)
  clear_has_myname();
  return myname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JoinRequest::set_allocated_myname(::std::string* myname) {
  if (myname != NULL) {
    set_has_myname();
  } else {
    clear_has_myname();
  }
  myname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), myname);
  // @@protoc_insertion_point(field_set_allocated:raft_msg.JoinRequest.myname)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace raft_msg

// @@protoc_insertion_point(global_scope)
