// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_enum.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "raft_enum.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace raft_msg {

namespace protobuf_raft_5fenum_2eproto {


namespace {

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[4];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = { ~0u };
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "raft_enum.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void TableStruct::Shutdown() {
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\017raft_enum.proto\022\010raft_msg**\n\010JoinRole\022"
      "\016\n\nJoinServer\020\000\022\016\n\nJoinClient\020\001*I\n\022Comma"
      "ndResponseErr\022\020\n\014CMDWRONGPASS\020\000\022\017\n\013CMDRE"
      "DIRECT\020\001\022\020\n\014CMDUNKNOWERR\020\002*1\n\tJoinError\022"
      "\021\n\rJOINWRONGPASS\020\000\022\021\n\rJOINUNKNOWERR\020\001*L\n"
      "\013CommandType\022\022\n\016RAFT_EVENT_GET\020\000\022\022\n\016RAFT"
      "_EVENT_PUT\020\001\022\025\n\021RAFT_EVENT_DELETE\020\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 275);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "raft_enum.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_raft_5fenum_2eproto

const ::google::protobuf::EnumDescriptor* JoinRole_descriptor() {
  protobuf_raft_5fenum_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_raft_5fenum_2eproto::file_level_enum_descriptors[0];
}
bool JoinRole_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* CommandResponseErr_descriptor() {
  protobuf_raft_5fenum_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_raft_5fenum_2eproto::file_level_enum_descriptors[1];
}
bool CommandResponseErr_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* JoinError_descriptor() {
  protobuf_raft_5fenum_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_raft_5fenum_2eproto::file_level_enum_descriptors[2];
}
bool JoinError_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* CommandType_descriptor() {
  protobuf_raft_5fenum_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_raft_5fenum_2eproto::file_level_enum_descriptors[3];
}
bool CommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace raft_msg

// @@protoc_insertion_point(global_scope)
