// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote_request.proto

#ifndef PROTOBUF_vote_5frequest_2eproto__INCLUDED
#define PROTOBUF_vote_5frequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace raft_msg {
class VoteRequest;
class VoteRequestDefaultTypeInternal;
extern VoteRequestDefaultTypeInternal _VoteRequest_default_instance_;
}  // namespace raft_msg

namespace raft_msg {

namespace protobuf_vote_5frequest_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_vote_5frequest_2eproto

// ===================================================================

class VoteRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_msg.VoteRequest) */ {
 public:
  VoteRequest();
  virtual ~VoteRequest();

  VoteRequest(const VoteRequest& from);

  inline VoteRequest& operator=(const VoteRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VoteRequest& default_instance();

  static inline const VoteRequest* internal_default_instance() {
    return reinterpret_cast<const VoteRequest*>(
               &_VoteRequest_default_instance_);
  }

  void Swap(VoteRequest* other);

  // implements Message ----------------------------------------------

  inline VoteRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  VoteRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const VoteRequest& from);
  void MergeFrom(const VoteRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(VoteRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 term = 1;
  bool has_term() const;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // required uint64 last_log_index = 2;
  bool has_last_log_index() const;
  void clear_last_log_index();
  static const int kLastLogIndexFieldNumber = 2;
  ::google::protobuf::uint64 last_log_index() const;
  void set_last_log_index(::google::protobuf::uint64 value);

  // required uint64 last_log_term = 3;
  bool has_last_log_term() const;
  void clear_last_log_term();
  static const int kLastLogTermFieldNumber = 3;
  ::google::protobuf::uint64 last_log_term() const;
  void set_last_log_term(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raft_msg.VoteRequest)
 private:
  void set_has_term();
  void clear_has_term();
  void set_has_last_log_index();
  void clear_has_last_log_index();
  void set_has_last_log_term();
  void clear_has_last_log_term();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 last_log_index_;
  ::google::protobuf::uint64 last_log_term_;
  friend struct  protobuf_vote_5frequest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// VoteRequest

// required uint64 term = 1;
inline bool VoteRequest::has_term() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VoteRequest::set_has_term() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VoteRequest::clear_has_term() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VoteRequest::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
  clear_has_term();
}
inline ::google::protobuf::uint64 VoteRequest::term() const {
  // @@protoc_insertion_point(field_get:raft_msg.VoteRequest.term)
  return term_;
}
inline void VoteRequest::set_term(::google::protobuf::uint64 value) {
  set_has_term();
  term_ = value;
  // @@protoc_insertion_point(field_set:raft_msg.VoteRequest.term)
}

// required uint64 last_log_index = 2;
inline bool VoteRequest::has_last_log_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VoteRequest::set_has_last_log_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VoteRequest::clear_has_last_log_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VoteRequest::clear_last_log_index() {
  last_log_index_ = GOOGLE_ULONGLONG(0);
  clear_has_last_log_index();
}
inline ::google::protobuf::uint64 VoteRequest::last_log_index() const {
  // @@protoc_insertion_point(field_get:raft_msg.VoteRequest.last_log_index)
  return last_log_index_;
}
inline void VoteRequest::set_last_log_index(::google::protobuf::uint64 value) {
  set_has_last_log_index();
  last_log_index_ = value;
  // @@protoc_insertion_point(field_set:raft_msg.VoteRequest.last_log_index)
}

// required uint64 last_log_term = 3;
inline bool VoteRequest::has_last_log_term() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void VoteRequest::set_has_last_log_term() {
  _has_bits_[0] |= 0x00000004u;
}
inline void VoteRequest::clear_has_last_log_term() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void VoteRequest::clear_last_log_term() {
  last_log_term_ = GOOGLE_ULONGLONG(0);
  clear_has_last_log_term();
}
inline ::google::protobuf::uint64 VoteRequest::last_log_term() const {
  // @@protoc_insertion_point(field_get:raft_msg.VoteRequest.last_log_term)
  return last_log_term_;
}
inline void VoteRequest::set_last_log_term(::google::protobuf::uint64 value) {
  set_has_last_log_term();
  last_log_term_ = value;
  // @@protoc_insertion_point(field_set:raft_msg.VoteRequest.last_log_term)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace raft_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vote_5frequest_2eproto__INCLUDED
